let User,CustomErrorHandler;_228‍.x([["default",()=>_228‍.o]]);_228‍.w("../../models",[["User",["User"],function(v){User=v}]]);_228‍.w("../../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const userController = {
  async me(req, res, next) {
    try {

      const user = await User.findOne({ _id: req.user._id });

      if (!user) {
        return next(CustomErrorHandler.notFound());
      }
      res.json(user);
    } catch (err) { return next(err)}
   
  },
};

_228‍.d(userController);
